### ISSUE TITLE
No syntax highlight if I do not specify "Set syntax: ini"

### ISSUE THREAD

**Issue by imnotril** [jwortmann/ini-syntax#15]
every time I open an ini or reg file the editor does not highlight the syntax if I do not specify it manually, this means that every time I open a file I have to put the command "Set syntax: INI", something very tedious if you deal with many ini files.

**Comment by imnotril** [comment]
actually this is easy to solve if you configure it in `View` **>** `Syntax` **>** `Open all with current extension as ...`, but it should be implemented with the package

**Comment by jwortmann** [comment]
It's already specified in the package:
https://github.com/jwortmann/ini-syntax/blob/0e968846401e13245b9653c74d3b13e0592d23b6/INI.sublime-syntax#L7-L11

Perhaps you have an override or an alternative package which also registers for INI files?

**Comment by imnotril** [comment]
as far as i know, i dont have any package that interferes with INI files, and i have very few packages installed, although it could be

btw, why this package aslo syntax highlight .editorconfig files??
![image](https://user-images.githubusercontent.com/116313217/202870888-0c18568f-37e0-472b-a7fc-e7eee8c401e8.png)

**Comment by jwortmann** [comment]
It could also be some kind of caching issue, I've recently seen several reports about strange behavior after Sublime Text or Package Control updates. You could run `sublime.cache_path()` and try to delete that directory to clear the syntax caches from all packages, and see if that helps.

Or to confirm that you don't have any other package interfering with the syntax somehow, you could start ST in safe mode (`subl --safe-mode`), install Package Control and the INI package, and then open an INI file. This way it should work (tm) that the syntax gets automatically applied.

> btw, why this package aslo syntax highlight .editorconfig files??

Some time ago there was another INI package on Package Control, but the syntax wasn't very good and the package was unmaintained, so I asked to replace that package with this one. In the course of this it was requested to add missing file extension from the old package here to achieve feature parity, which included .editorconfig files. Also the .editorconfig format is basically like INI files, so it seems reasonable to include it in this package.

**Comment by imnotril** [comment]
@jwortmann I have tested and if it works in safe mode with clean cache, since there are no packages that interfere with INI files, I would assume it is a caching issue as you said
