### ISSUE TITLE
INI is not showing up in packagecontrol

### ISSUE THREAD

**Issue by txtsd** [jwortmann/ini-syntax#5]
And there is an existing package called [INI](https://packagecontrol.io/packages/INI)

**Comment by jwortmann** [comment]
It should be available soon: https://github.com/wbond/package_control_channel/pull/8020

If you have the old INI package installed, it will automatically be upgraded to this package as soon as that PR gets merged. I will close this issue when that happens.

**Comment by txtsd** [comment]
Awesome! Thanks!

**Comment by jwortmann** [comment]
The PR has been merged, so Package Control should automatically pick up the new version from this repository now.
